import { PrismaClient } from '@prisma/client';
import { subDays } from 'date-fns';

const prisma = new PrismaClient();

const now = new Date();

const projects = [
  {
    githubId: 584759280,
    name: 'n8n',
    fullName: 'n8n-io/n8n',
    owner: 'n8n-io',
    avatarUrl: 'https://avatars.githubusercontent.com/u/584759280?v=4',
    htmlUrl: 'https://github.com/n8n-io/n8n',
    description: 'Free and source-available fair-code licensed workflow automation tool. With a visual editor.',
    language: 'TypeScript',
    stars: 65000,
    forks: 8500,
    openIssues: 210,
    createdAt: subDays(now, 800),
    updatedAt: subDays(now, 1),
    pushedAt: subDays(now, 1),
    category: 'all-time',
  },
  {
    githubId: 10270250,
    name: 'react',
    fullName: 'facebook/react',
    owner: 'facebook',
    avatarUrl: 'https://avatars.githubusercontent.com/u/69631?v=4',
    htmlUrl: 'https://github.com/facebook/react',
    description: 'The library for web and native user interfaces.',
    language: 'JavaScript',
    stars: 225000,
    forks: 46000,
    openIssues: 980,
    createdAt: subDays(now, 2500),
    updatedAt: subDays(now, 2),
    pushedAt: subDays(now, 2),
    category: 'all-time',
  },
  {
    githubId: 134931630,
    name: 'next.js',
    fullName: 'vercel/next.js',
    owner: 'vercel',
    avatarUrl: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    htmlUrl: 'https://github.com/vercel/next.js',
    description: 'The React Framework for the Web',
    language: 'JavaScript',
    stars: 125000,
    forks: 26000,
    openIssues: 2100,
    createdAt: subDays(now, 1500),
    updatedAt: subDays(now, 1),
    pushedAt: subDays(now, 1),
    category: 'all-time',
  },
  {
    githubId: 11730342,
    name: 'vue',
    fullName: 'vuejs/vue',
    owner: 'vuejs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6128107?v=4',
    htmlUrl: 'https://github.com/vuejs/vue',
    description: 'This is the repo for Vue 2. For Vue 3, go to vuejs/core',
    language: 'JavaScript',
    stars: 210000,
    forks: 35000,
    openIssues: 420,
    createdAt: subDays(now, 2800),
    updatedAt: subDays(now, 5),
    pushedAt: subDays(now, 5),
    category: 'all-time',
  },
  {
    githubId: 123456789,
    name: 'tailwindcss',
    fullName: 'tailwindlabs/tailwindcss',
    owner: 'tailwindlabs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/67109815?v=4',
    htmlUrl: 'https://github.com/tailwindlabs/tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development.',
    language: 'JavaScript',
    stars: 82000,
    forks: 4200,
    openIssues: 25,
    createdAt: subDays(now, 1200),
    updatedAt: subDays(now, 3),
    pushedAt: subDays(now, 2),
    category: 'all-time',
  },
  {
    githubId: 200000001,
    name: 'hono',
    fullName: 'honojs/hono',
    owner: 'honojs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/83456083?v=4',
    htmlUrl: 'https://github.com/honojs/hono',
    description: 'Fast, Lightweight, Web-standards. Works on Cloudflare Workers, Fastly.',
    language: 'TypeScript',
    stars: 28000,
    forks: 1200,
    openIssues: 45,
    createdAt: subDays(now, 25),
    updatedAt: subDays(now, 1),
    pushedAt: subDays(now, 1),
    category: 'monthly',
  },
  {
    githubId: 200000002,
    name: 'bun',
    fullName: 'oven-sh/bun',
    owner: 'oven-sh',
    avatarUrl: 'https://avatars.githubusercontent.com/u/81489002?v=4',
    htmlUrl: 'https://github.com/oven-sh/bun',
    description: 'Incredibly fast JavaScript runtime, bundler, test runner.',
    language: 'Zig',
    stars: 75000,
    forks: 2300,
    openIssues: 1100,
    createdAt: subDays(now, 20),
    updatedAt: subDays(now, 1),
    pushedAt: subDays(now, 1),
    category: 'monthly',
  },
  {
    githubId: 200000003,
    name: 'lucide',
    fullName: 'lucide-icons/lucide',
    owner: 'lucide-icons',
    avatarUrl: 'https://avatars.githubusercontent.com/u/77888015?v=4',
    htmlUrl: 'https://github.com/lucide-icons/lucide',
    description: 'Beautiful & consistent icon toolkit made by the community.',
    language: 'JavaScript',
    stars: 18000,
    forks: 850,
    openIssues: 150,
    createdAt: subDays(now, 15),
    updatedAt: subDays(now, 2),
    pushedAt: subDays(now, 2),
    category: 'monthly',
  },
  {
    githubId: 300000001,
    name: 'shadcn-ui',
    fullName: 'shadcn-ui/ui',
    owner: 'shadcn-ui',
    avatarUrl: 'https://avatars.githubusercontent.com/u/139895814?v=4',
    htmlUrl: 'https://github.com/shadcn-ui/ui',
    description: 'Beautifully designed components built with Radix UI and Tailwind.',
    language: 'TypeScript',
    stars: 65000,
    forks: 6800,
    openIssues: 230,
    createdAt: subDays(now, 6),
    updatedAt: subDays(now, 1),
    pushedAt: subDays(now, 1),
    category: 'weekly',
  },
  {
    githubId: 300000002,
    name: 't3-app',
    fullName: 't3-oss/create-t3-app',
    owner: 't3-oss',
    avatarUrl: 'https://avatars.githubusercontent.com/u/103018639?v=4',
    htmlUrl: 'https://github.com/t3-oss/create-t3-app',
    description: 'The best way to start a full-stack, typesafe Next.js app.',
    language: 'TypeScript',
    stars: 25000,
    forks: 1200,
    openIssues: 55,
    createdAt: subDays(now, 5),
    updatedAt: subDays(now, 2),
    pushedAt: subDays(now, 1),
    category: 'weekly',
  },
  {
    githubId: 400000001,
    name: 'trpc',
    fullName: 'trpc/trpc',
    owner: 'trpc',
    avatarUrl: 'https://avatars.githubusercontent.com/u/78011399?v=4',
    htmlUrl: 'https://github.com/trpc/trpc',
    description: 'End-to-end typesafe APIs made easy.',
    language: 'TypeScript',
    stars: 35000,
    forks: 1100,
    openIssues: 85,
    createdAt: subDays(now, 4),
    updatedAt: subDays(now, 1),
    pushedAt: subDays(now, 1),
    category: 'active',
  },
  {
    githubId: 400000002,
    name: 'zod',
    fullName: 'colinhacks/zod',
    owner: 'colinhacks',
    avatarUrl: 'https://avatars.githubusercontent.com/u/3084745?v=4',
    htmlUrl: 'https://github.com/colinhacks/zod',
    description: 'TypeScript first schema validation with static type inference.',
    language: 'TypeScript',
    stars: 38000,
    forks: 920,
    openIssues: 280,
    createdAt: subDays(now, 3),
    updatedAt: subDays(now, 2),
    pushedAt: subDays(now, 2),
    category: 'active',
  },
];

async function main() {
  console.log('Seeding database...');

  for (const project of projects) {
    await prisma.project.upsert({
      where: { githubId: project.githubId },
      update: project,
      create: project,
    });
    console.log(`Upserted: ${project.fullName}`);
  }

  await prisma.collection.upsert({
    where: { githubId: 10270250 },
    update: {},
    create: {
      githubId: 10270250,
      note: 'Essential UI library',
    },
  });

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
