import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const seedProjects = [
  // 全站总榜 - 高星项目
  {
    githubId: 1,
    name: 'freeCodeCamp',
    fullName: 'freeCodeCamp/freeCodeCamp',
    owner: 'freeCodeCamp',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/9892522?v=4',
    description: 'freeCodeCamp.org is a friendly community where you can learn to code for free.',
    language: 'TypeScript',
    stars: 410000,
    starsPrev: 400000,
    starsGrowth: 2.5,
    growthTier: 'rising',
    forks: 39000,
    issues: 120,
    createdAt: new Date('2014-12-24'),
    pushedAt: new Date('2024-12-10'),
    htmlUrl: 'https://github.com/freeCodeCamp/freeCodeCamp',
  },
  {
    githubId: 2,
    name: 'free-programming-books',
    fullName: 'EbookFoundation/free-programming-books',
    owner: 'EbookFoundation',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/14127308?v=4',
    description: ':books: Freely available programming books',
    language: 'HTML',
    stars: 340000,
    starsPrev: 335000,
    starsGrowth: 1.5,
    growthTier: 'none',
    forks: 62000,
    issues: 45,
    createdAt: new Date('2013-10-11'),
    pushedAt: new Date('2024-12-12'),
    htmlUrl: 'https://github.com/EbookFoundation/free-programming-books',
  },
  {
    githubId: 3,
    name: 'awesome',
    fullName: 'sindresorhus/awesome',
    owner: 'sindresorhus',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/170270?v=4',
    description: '😎 Awesome lists about all kinds of interesting topics',
    language: null,
    stars: 340000,
    starsPrev: 338000,
    starsGrowth: 0.6,
    growthTier: 'none',
    forks: 28000,
    issues: 60,
    createdAt: new Date('2014-07-11'),
    pushedAt: new Date('2024-12-08'),
    htmlUrl: 'https://github.com/sindresorhus/awesome',
  },
  {
    githubId: 4,
    name: 'public-apis',
    fullName: 'public-apis/public-apis',
    owner: 'public-apis',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/51121562?v=4',
    description: 'A collective list of free APIs',
    language: 'Python',
    stars: 320000,
    starsPrev: 310000,
    starsGrowth: 3.2,
    growthTier: 'rising',
    forks: 34000,
    issues: 80,
    createdAt: new Date('2016-03-20'),
    pushedAt: new Date('2024-12-11'),
    htmlUrl: 'https://github.com/public-apis/public-apis',
  },
  {
    githubId: 5,
    name: 'coding-interview-university',
    fullName: 'jwasham/coding-interview-university',
    owner: 'jwasham',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/3771963?v=4',
    description: 'A complete computer science study plan to become a software engineer.',
    language: null,
    stars: 310000,
    starsPrev: 305000,
    starsGrowth: 1.6,
    growthTier: 'none',
    forks: 76000,
    issues: 55,
    createdAt: new Date('2016-06-06'),
    pushedAt: new Date('2024-12-09'),
    htmlUrl: 'https://github.com/jwasham/coding-interview-university',
  },
  // 本月新秀 - 近期创建
  {
    githubId: 101,
    name: 'next-ai-starter',
    fullName: 'vercel/next-ai-starter',
    owner: 'vercel',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    description: 'AI-powered Next.js starter template with streaming support',
    language: 'TypeScript',
    stars: 8500,
    starsPrev: 1000,
    starsGrowth: 750,
    growthTier: 'explosive',
    forks: 420,
    issues: 12,
    createdAt: new Date('2024-11-15'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/vercel/next-ai-starter',
  },
  {
    githubId: 102,
    name: 'rust-web-framework',
    fullName: 'tokio-rs/rust-web-framework',
    owner: 'tokio-rs',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/20248544?v=4',
    description: 'Blazing fast web framework for Rust',
    language: 'Rust',
    stars: 7200,
    starsPrev: 2000,
    starsGrowth: 260,
    growthTier: 'explosive',
    forks: 280,
    issues: 8,
    createdAt: new Date('2024-11-20'),
    pushedAt: new Date('2024-12-13'),
    htmlUrl: 'https://github.com/tokio-rs/rust-web-framework',
  },
  {
    githubId: 103,
    name: 'go-microservices-kit',
    fullName: 'google/go-microservices-kit',
    owner: 'google',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/1342004?v=4',
    description: 'Production-ready microservices starter kit for Go',
    language: 'Go',
    stars: 6800,
    starsPrev: 2500,
    starsGrowth: 172,
    growthTier: 'hot',
    forks: 350,
    issues: 15,
    createdAt: new Date('2024-11-25'),
    pushedAt: new Date('2024-12-12'),
    htmlUrl: 'https://github.com/google/go-microservices-kit',
  },
  {
    githubId: 104,
    name: 'python-ml-pipeline',
    fullName: 'microsoft/python-ml-pipeline',
    owner: 'microsoft',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    description: 'End-to-end ML pipeline toolkit with MLOps best practices',
    language: 'Python',
    stars: 5900,
    starsPrev: 2800,
    starsGrowth: 110,
    growthTier: 'hot',
    forks: 410,
    issues: 22,
    createdAt: new Date('2024-11-28'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/microsoft/python-ml-pipeline',
  },
  {
    githubId: 105,
    name: 'react-native-ui-kit',
    fullName: 'facebook/react-native-ui-kit',
    owner: 'facebook',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/69631?v=4',
    description: 'Modern UI component library for React Native',
    language: 'TypeScript',
    stars: 5200,
    starsPrev: 3000,
    starsGrowth: 73,
    growthTier: 'rising',
    forks: 180,
    issues: 6,
    createdAt: new Date('2024-12-01'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/facebook/react-native-ui-kit',
  },
  // 最近活跃 - 近期更新
  {
    githubId: 201,
    name: 'react',
    fullName: 'facebook/react',
    owner: 'facebook',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/69631?v=4',
    description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    language: 'JavaScript',
    stars: 230000,
    starsPrev: 228000,
    starsGrowth: 0.9,
    growthTier: 'none',
    forks: 48000,
    issues: 850,
    createdAt: new Date('2013-05-24'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/facebook/react',
  },
  {
    githubId: 202,
    name: 'tensorflow',
    fullName: 'tensorflow/tensorflow',
    owner: 'tensorflow',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/15658638?v=4',
    description: 'An Open Source Machine Learning Framework for Everyone',
    language: 'C++',
    stars: 185000,
    starsPrev: 183000,
    starsGrowth: 1.1,
    growthTier: 'none',
    forks: 74000,
    issues: 1200,
    createdAt: new Date('2015-11-07'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/tensorflow/tensorflow',
  },
  {
    githubId: 203,
    name: 'vscode',
    fullName: 'microsoft/vscode',
    owner: 'microsoft',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    description: 'Visual Studio Code',
    language: 'TypeScript',
    stars: 165000,
    starsPrev: 163500,
    starsGrowth: 0.9,
    growthTier: 'none',
    forks: 29000,
    issues: 5200,
    createdAt: new Date('2015-09-03'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/microsoft/vscode',
  },
  {
    githubId: 204,
    name: 'next.js',
    fullName: 'vercel/next.js',
    owner: 'vercel',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    description: 'The React Framework',
    language: 'TypeScript',
    stars: 127000,
    starsPrev: 125000,
    starsGrowth: 1.6,
    growthTier: 'none',
    forks: 27000,
    issues: 1100,
    createdAt: new Date('2016-10-05'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/vercel/next.js',
  },
  {
    githubId: 205,
    name: 'kubernetes',
    fullName: 'kubernetes/kubernetes',
    owner: 'kubernetes',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/13629408?v=4',
    description: 'Production-Grade Container Scheduling and Management',
    language: 'Go',
    stars: 112000,
    starsPrev: 111000,
    starsGrowth: 0.9,
    growthTier: 'none',
    forks: 39000,
    issues: 1800,
    createdAt: new Date('2014-06-06'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/kubernetes/kubernetes',
  },
  // 攀升榜 - 近期创建且快速增长
  {
    githubId: 301,
    name: 'ai-code-assistant',
    fullName: 'openai/ai-code-assistant',
    owner: 'openai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    description: 'AI-powered code assistant with context-aware suggestions',
    language: 'Python',
    stars: 12500,
    starsPrev: 2000,
    starsGrowth: 525,
    growthTier: 'explosive',
    forks: 890,
    issues: 45,
    createdAt: new Date('2024-12-05'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/openai/ai-code-assistant',
  },
  {
    githubId: 302,
    name: 'edge-runtime',
    fullName: 'cloudflare/edge-runtime',
    owner: 'cloudflare',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/314135?v=4',
    description: 'Next-generation edge computing runtime',
    language: 'Rust',
    stars: 9800,
    starsPrev: 2500,
    starsGrowth: 292,
    growthTier: 'explosive',
    forks: 420,
    issues: 28,
    createdAt: new Date('2024-12-06'),
    pushedAt: new Date('2024-12-13'),
    htmlUrl: 'https://github.com/cloudflare/edge-runtime',
  },
  {
    githubId: 303,
    name: 'realtime-sync-engine',
    fullName: 'supabase/realtime-sync-engine',
    owner: 'supabase',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/54469796?v=4',
    description: 'Real-time data synchronization engine for PostgreSQL',
    language: 'Elixir',
    stars: 8700,
    starsPrev: 3000,
    starsGrowth: 190,
    growthTier: 'hot',
    forks: 310,
    issues: 18,
    createdAt: new Date('2024-12-07'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/supabase/realtime-sync-engine',
  },
  {
    githubId: 304,
    name: 'wasm-compiler',
    fullName: 'bytecodealliance/wasm-compiler',
    owner: 'bytecodealliance',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/54038801?v=4',
    description: 'High-performance WebAssembly compiler toolchain',
    language: 'Rust',
    stars: 7600,
    starsPrev: 3200,
    starsGrowth: 137,
    growthTier: 'hot',
    forks: 280,
    issues: 22,
    createdAt: new Date('2024-12-08'),
    pushedAt: new Date('2024-12-13'),
    htmlUrl: 'https://github.com/bytecodealliance/wasm-compiler',
  },
  {
    githubId: 305,
    name: 'vector-db-lite',
    fullName: 'pinecone-io/vector-db-lite',
    owner: 'pinecone-io',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/53613428?v=4',
    description: 'Lightweight vector database for AI applications',
    language: 'Python',
    stars: 6500,
    starsPrev: 3500,
    starsGrowth: 85,
    growthTier: 'rising',
    forks: 190,
    issues: 12,
    createdAt: new Date('2024-12-09'),
    pushedAt: new Date('2024-12-14'),
    htmlUrl: 'https://github.com/pinecone-io/vector-db-lite',
  },
];

async function main() {
  console.log('🌱 Starting database seeding...');

  // 清空现有数据
  await prisma.collection.deleteMany();
  await prisma.project.deleteMany();

  console.log('🗑️  Cleared existing data');

  // 插入项目数据
  for (const project of seedProjects) {
    await prisma.project.create({
      data: project,
    });
    console.log(`✅ Created project: ${project.fullName} (Growth: ${project.growthTier})`);
  }

  // 添加一些收藏
  const collections = [1, 2, 4, 101, 201, 301];
  for (const githubId of collections) {
    await prisma.collection.create({
      data: { githubId },
    });
    console.log(`⭐ Added collection for githubId: ${githubId}`);
  }

  console.log('✨ Database seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
